language: node_js

cache:
  directories:
  - node_modules

node_js:
  - '14.17.0'
  
branches:
  only:
   - main

script:
  - npm start
  - npm test

notifications:
  slack: puebascircle:TO02QRx5beoDFlwxJVV1xpmm