language: node_js

cache:
  directories:
  - node_modules
  - ~/.npm

node_js:
  - '14.17.0'
  
branches:
  only:
   - main

script:
  - npm test

deploy:
  provider: heroku
  api_key: "$HEROKU_KEY"
  on:
    branch: main
  app: parcial-ci

notifications:
  slack: puebascircle:TO02QRx5beoDFlwxJVV1xpmm